name: Tests with uv

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  uv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install EGL mesa - required for Panda3D renderer
        run: sudo apt-get update && sudo apt-get install -qqy libegl1-mesa libegl1-mesa-dev

      - name: Caching of the happypose installation and data
        uses: actions/cache@v4
        with:
          path: local_data
          key: data

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install happypose
        run: uv sync --extra cpu --extra pypi

      - name: Download pre-trained models required for tests
        run: |
          mkdir -p local_data
          uv run python -m happypose.toolbox.utils.download \
            --megapose_models \
            --examples \
              barbecue-sauce \
            --cosypose_models  \
              detector-bop-hope-pbr--15246 \
              coarse-bop-hope-pbr--225203 \
              refiner-bop-hope-pbr--955392

      - name: Run tests
        run: |
          uv run python -m unittest
          uv run pytest tests -v
